### PR TITLE
Return JSON with 'redirect_to' when handle_failed_second_factor

### PR DESCRIPTION
**Pull request by Kevinrob**
With that, we can have anonymous page that make authenticated AJAX call. 
Client side, we can handle the redirection to the "two factor" page.

### CODE REVIEW

**Comment by Kevinrob** [comment]
@Houdini Hi 👋 Can you check this PR and tell me if you have any remarks about it?

**Comment by Houdini** [comment]
Hi, sorry, I missed this.
Thanks for remind me again.

Do you think it's ok to return not 200 status in json api?
May be it's better to return

```
{"auth": false, "reason": "...", "redirect_to": "..."}
```

What do you think?

**Comment by Kevinrob** [comment]
Yeah, it's an error, I think that it's okay to not returning a 200 status code.  

If we return a custom JSON with a 200, the client that make the HTTP request should guess what is the response. If we return an error, it's easier to know what is the content.

**Comment by Kevinrob** [comment]
@Houdini Is there anything I can do about this PR? 😃

**Comment by Kevinrob** [comment]
@Houdini ping? 😊

**Comment by Houdini** [comment]
Hey, it looks ok to me, thanks for commit

**Pull request merged**
